# Jenkins
jenkins_home: /vdb/jenkins
java_packages:
  - java-1.8.0-openjdk
jenkins_admin_token: "{{ jenkins_admin_token_secret }}"

# runSetupWizard=false is default
# Add the CSP so we can embed galaxy on WF testing pages / display HTML
jenkins_java_options: "-Djenkins.install.runSetupWizard=false -Dhudson.model.DirectoryBrowserSupport.CSP=\"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'unsafe-inline'; frame-src *;\""

# Certbot
certbot_auth_method: --webroot
certbot_well_known_root: /srv/nginx/_well-known_root
certbot_share_key_users:
  - nginx

certbot_post_renewal: |
    systemctl restart nginx || true

# NGINX
nginx_enable_default_server: false
nginx_ssl_servers:
  - build
nginx_conf_http:
  client_max_body_size: 1g
nginx_remove_default_vhost: true

# Nginx Letsencrypt bindings
nginx_ssl_role: usegalaxy-eu.certbot
nginx_conf_ssl_certificate: /etc/ssl/certs/fullchain.pem
nginx_conf_ssl_certificate_key: /etc/ssl/user/privkey-nginx.pem
