---
# create_user task
user_name: galaxy
user_uid: 999
user_comment: Galaxy service
user_group_name: galaxy
user_gid: 999

galaxy_user:
  name: "{{ user_name }}"
__galaxy_user_group: "{{ user_group_name }}"
galaxy_root: /opt/galaxy
galaxy_server_dir: "{{ galaxy_root }}/server"
galaxy_venv_dir: "{{ galaxy_root }}/venv"
galaxy_config_dir: "{{ galaxy_root }}/config"
galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.yml"

# Autofs
autofs_service.install: true
autofs_service.enable: true
nfs_kernel_tuning: true

autofs_mount_points:
  - data
  - usrlocal

autofs_conf_files:
  data:
    - 0       -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/depot/&
    - 1       -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/depot/&
    - 2       -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/depot/&
    - 3       -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/depot/&
    - 4       -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/depot/&
    - 5       -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/depot/&
    - 6       -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/depot/&
    - 7       -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/depot/&
    - dp01    -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/dataplant01
    - dnb01   -rw,hard,nosuid      ufr-dyn.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
    - dnb02   -rw,hard,nosuid      ufr-dyn.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
    - dnb03   -rw,hard,nosuid      ufr-dyn.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
    - dnb04   -rw,hard,nosuid      ufr-dyn.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
    - dnb05   -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/dnb01/&
    - dnb06   -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/dnb06
    - dnb07   -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/dnb07
    - dnb08   -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/dnb08
    - db      -rw,hard,nosuid      ufr-dyn.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
    - gxtst   -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/ws01/galaxy-sync/test
    - gxkey   -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/ws01/galaxy-sync/main
    - jwd     -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/ws01/&
    - jwd01   -rw,hard,nosuid      zfs1.galaxyproject.eu:/export/&
  usrlocal:
    - /opt/galaxy        -rw,hard,nosuid,nconnect=2      denbi.svm.bwsfs.uni-freiburg.de:/ws01/galaxy-sync/main

# SystemD
galaxy_systemd_mode: ""
galaxy_systemd_celery: true
galaxy_systemd_celery_pool: threads
galaxy_systemd_celery_workers: 1
galaxy_systemd_celery_concurrency: 32
galaxy_systemd_celery_log_level: DEBUG
galaxy_systemd_celery_env: ""
galaxy_systemd_celery_beat_schedule_path: "/opt/galaxy/celery/celery-beat-schedule"
galaxy_systemd_memory_limit_celery: 20

# Flower
flower_python_version: python38
flower_app_dir: /opt/galaxy/
flower_python_path: server/lib
flower_venv_dir: /opt/galaxy/venv
flower_app_name: galaxy.celery

flower_persistent: "True"

flower_broker_api: "https://flower:{{ rabbitmq_password_flower }}@{{ rabbitmq_url }}/api/vhosts"
flower_broker_url: "amqp://flower:{{ rabbitmq_password_flower }}@{{ rabbitmq_url }}:5671/galaxy?ssl=true"
