---
# Autofs
usegalaxy_eu_autofs_mounts:
 - data

# HTCondor
condor_host: "manager.vgcn.galaxyproject.eu"
condor_allow_write: "10.5.68.0/24, 10.19.0.0/16, 132.230.68.0/24, *.bi.uni-freiburg.de"
condor_daemons:
    - COLLECTOR
    - MASTER
    - NEGOTIATOR
    - SCHEDD
condor_allow_negotiator: $(ALLOW_WRITE)
condor_allow_administrator: "$(ALLOW_NEGOTIATOR)"
#condor_network_interface: ens2
