---
galaxy_custom_site_base_css: '#masthead { background-color: #003399;}'

galaxy_custom_sites:
  - name: assembly
    brand: Genome Assembly
    custom_css: |
      #masthead {
          background: linear-gradient(20deg, rgb(7, 40, 98) 0%, rgb(69, 122, 184) 48%, rgba(165,204,210,0.9676562309265136) 74%, rgb(228, 195, 131) 92%, rgb(203, 119, 79) 100%);
      }
      @keyframes fly-right-one {
          0% {
              transform: translateY(-2vh) translateX(-55vw) scale(0.5);
          }
          15% {
              transform: translateY(0vh) translateX(-45vw) scale(0.4);
          }
          30% {
              transform: translateY(-2vh) translateX(-25vw) scale(0.6);
          }
          45% {
              transform: translateY(1vh) translateX(-5vw) scale(0.45);
          }
          60% {
              transform: translateY(-2vh) translateX(16vw) scale(0.5);
          }
          75% {
              transform: translateY(0vh) translateX(28vw) scale(0.45);
          }
          100% {
              transform: translateY(-1vh) translateX(48vw) scale(0.45);
          }
      }
      @keyframes fly-right-two {
          0% {
              transform: translateY(2vh) translateX(-55vw) scale(0.5);
          }
          25% {
              transform: translateY(0vh) translateX(-35vw) scale(0.4);
          }
          50% {
              transform: translateY(-2vh) translateX(-10vw) scale(0.6);
          }
          75% {
              transform: translateY(1vh) translateX(19vw) scale(0.45);
          }
          100% {
              transform: translateY(0.5vh) translateX(48vw) scale(0.45);
          }
      }

       @keyframes fly-cycle {
           100% {
               background-position: -900px 0;
          }
      }

      #masthead:before {
      position: absolute;
      content: "";
      width: 88px;
      height: 125px;
      background-size: auto 100%;
      animation: fly-cycle  1s steps(10) infinite, fly-right-one  9s linear infinite;
      /* back-up alternative https://usegalaxy-eu.github.io/assets/media/bird-cells-new.svg */
      background-image: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/174479/bird-cells-new.svg);
      }

      #masthead:after {
      position: absolute;
      content: "";
      width: 88px;
      height: 125px;
      background-size: auto 100%;
      animation: fly-cycle  1s steps(10) infinite, fly-right-two 15s linear infinite;
      /* back-up alternative https://usegalaxy-eu.github.io/assets/media/bird-cells-new.svg */
      background-image: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/174479/bird-cells-new.svg);
      }
  - name: nanopore
    brand: Nanopore
  - name: erasmusmc
    brand: ErasmucMC
  - name: climate
    brand: Climate
    custom_css: |
        #masthead {
          background: linear-gradient(to right,#2171b5 0.00%,#2171b5 0.83%,#c6dbef 0.83%,#c6dbef 1.65%,#9ecae1 1.65%,#9ecae1 2.48%,#fee0d2 2.48%,#fee0d2 3.31%,#6baed6 3.31%,#6baed6 4.13%,#9ecae1 4.13%,#9ecae1 4.96%,#08519c 4.96%,#08519c 5.79%,#08306b 5.79%,#08306b 6.61%,#2171b5 6.61%,#2171b5 7.44%,#4292c6 7.44%,#4292c6 8.26%,#9ecae1 8.26%,#9ecae1 9.09%,#2171b5 9.09%,#2171b5 9.92%,#4292c6 9.92%,#4292c6 10.74%,#9ecae1 10.74%,#9ecae1 11.57%,#deebf7 11.57%,#deebf7 12.40%,#9ecae1 12.40%,#9ecae1 13.22%,#deebf7 13.22%,#deebf7 14.05%,#4292c6 14.05%,#4292c6 14.88%,#08519c 14.88%,#08519c 15.70%,#deebf7 15.70%,#deebf7 16.53%,#9ecae1 16.53%,#9ecae1 17.36%,#c6dbef 17.36%,#c6dbef 18.18%,#6baed6 18.18%,#6baed6 19.01%,#4292c6 19.01%,#4292c6 19.83%,#2171b5 19.83%,#2171b5 20.66%,#deebf7 20.66%,#deebf7 21.49%,#fcbba1 21.49%,#fcbba1 22.31%,#9ecae1 22.31%,#9ecae1 23.14%,#deebf7 23.14%,#deebf7 23.97%,#9ecae1 23.97%,#9ecae1 24.79%,#deebf7 24.79%,#deebf7 25.62%,#4292c6 25.62%,#4292c6 26.45%,#deebf7 26.45%,#deebf7 27.27%,#2171b5 27.27%,#2171b5 28.10%,#fee0d2 28.10%,#fee0d2 28.93%,#fcbba1 28.93%,#fcbba1 29.75%,#08519c 29.75%,#08519c 30.58%,#9ecae1 30.58%,#9ecae1 31.40%,#4292c6 31.40%,#4292c6 32.23%,#c6dbef 32.23%,#c6dbef 33.06%,#fee0d2 33.06%,#fee0d2 33.88%,#9ecae1 33.88%,#9ecae1 34.71%,#c6dbef 34.71%,#c6dbef 35.54%,#2171b5 35.54%,#2171b5 36.36%,#fcbba1 36.36%,#fcbba1 37.19%,#4292c6 37.19%,#4292c6 38.02%,#c6dbef 38.02%,#c6dbef 38.84%,#4292c6 38.84%,#4292c6 39.67%,#ef3b2c 39.67%,#ef3b2c 40.50%,#deebf7 40.50%,#deebf7 41.32%,#fee0d2 41.32%,#fee0d2 42.15%,#c6dbef 42.15%,#c6dbef 42.98%,#08306b 42.98%,#08306b 43.80%,#08519c 43.80%,#08519c 44.63%,#2171b5 44.63%,#2171b5 45.45%,#fcbba1 45.45%,#fcbba1 46.28%,#c6dbef 46.28%,#c6dbef 47.11%,#fcbba1 47.11%,#fcbba1 47.93%,#deebf7 47.93%,#deebf7 48.76%,#fcbba1 48.76%,#fcbba1 49.59%,#fc9272 49.59%,#fc9272 50.41%,#fee0d2 50.41%,#fee0d2 51.24%,#9ecae1 51.24%,#9ecae1 52.07%,#fcbba1 52.07%,#fcbba1 52.89%,#6baed6 52.89%,#6baed6 53.72%,#4292c6 53.72%,#4292c6 54.55%,#08306b 54.55%,#08306b 55.37%,#fee0d2 55.37%,#fee0d2 56.20%,#c6dbef 56.20%,#c6dbef 57.02%,#fcbba1 57.02%,#fcbba1 57.85%,#deebf7 57.85%,#deebf7 58.68%,#fcbba1 58.68%,#fcbba1 59.50%,#08519c 59.50%,#08519c 60.33%,#9ecae1 60.33%,#9ecae1 61.16%,#4292c6 61.16%,#4292c6 61.98%,#deebf7 61.98%,#deebf7 62.81%,#fcbba1 62.81%,#fcbba1 63.64%,#9ecae1 63.64%,#9ecae1 64.46%,#6baed6 64.46%,#6baed6 65.29%,#deebf7 65.29%,#deebf7 66.12%,#6baed6 66.12%,#6baed6 66.94%,#c6dbef 66.94%,#c6dbef 67.77%,#fcbba1 67.77%,#fcbba1 68.60%,#deebf7 68.60%,#deebf7 69.42%,#fee0d2 69.42%,#fee0d2 70.25%,#6baed6 70.25%,#6baed6 71.07%,#4292c6 71.07%,#4292c6 71.90%,#c6dbef 71.90%,#c6dbef 72.73%,#fcbba1 72.73%,#fcbba1 73.55%,#9ecae1 73.55%,#9ecae1 74.38%,#2171b5 74.38%,#2171b5 75.21%,#9ecae1 75.21%,#9ecae1 76.03%,#2171b5 76.03%,#2171b5 76.86%,#fc9272 76.86%,#fc9272 77.69%,#ef3b2c 77.69%,#ef3b2c 78.51%,#c6dbef 78.51%,#c6dbef 79.34%,#fb6a4a 79.34%,#fb6a4a 80.17%,#deebf7 80.17%,#deebf7 80.99%,#cb181d 80.99%,#cb181d 81.82%,#fcbba1 81.82%,#fcbba1 82.64%,#08519c 82.64%,#08519c 83.47%,#fcbba1 83.47%,#fcbba1 84.30%,#fc9272 84.30%,#fc9272 85.12%,#ef3b2c 85.12%,#ef3b2c 85.95%,#cb181d 85.95%,#cb181d 86.78%,#fcbba1 86.78%,#fcbba1 87.60%,#ef3b2c 87.60%,#ef3b2c 88.43%,#fb6a4a 88.43%,#fb6a4a 89.26%,#fcbba1 89.26%,#fcbba1 90.08%,#ef3b2c 90.08%,#ef3b2c 90.91%,#cb181d 90.91%,#cb181d 91.74%,#ef3b2c 91.74%,#ef3b2c 92.56%,#fc9272 92.56%,#fc9272 93.39%,#6baed6 93.39%,#6baed6 94.21%,#ef3b2c 94.21%,#ef3b2c 95.04%,#fc9272 95.04%,#fc9272 95.87%,#fee0d2 95.87%,#fee0d2 96.69%,#67000d 96.69%,#67000d 97.52%,#cb181d 97.52%,#cb181d 98.35%,#ef3b2c 98.35%,#ef3b2c 99.17%,#67000d 99.17%,#67000d 100.00%);
        }
        #masthead .navbar-brand {
          background: #3337;
          height: 100%;
          padding: 0.5em;
          left: 0px;
        }
        #masthead .navbar-nav > li .nav-link {
            color: white;
        }
        #masthead .navbar-nav > li {
            background: #3337;
        }
        #masthead .navbar-nav > li.active {
            background: #333e;
        }
  - name: hicexplorer
    brand: HiCExplorer
    wallpaper: true
    custom_css: |
        #masthead {
            background-image: url("/static/dist/hicexplorer.png");
            background-size: 340px;
        }
        #masthead .navbar-brand {
          background: #3337;
          height: 100%;
          padding: 0.5em;
          left: 0px;
        }
        #masthead .navbar-nav > li .nav-link {
            color: white;
        }
        #masthead .navbar-nav > li {
            background: #3337;
        }
        #masthead .navbar-nav > li.active {
            background: #333e;
        }
  - name: annotation
    brand: Genome Annotation
    wallpaper: true
    custom_css: |
        #masthead {
            background-image: url("/static/dist/annotation.png");
            background-size: 23%;
        }
        #masthead .navbar-brand {
          background: #3337;
          height: 100%;
          padding: 0.5em;
          left: 0px;
        }
        #masthead .navbar-nav > li .nav-link {
            color: white;
        }
        #masthead .navbar-nav > li {
            background: #3337;
        }
        #masthead .navbar-nav > li.active {
            background: #333e;
        }
  - name: metabolomics
    brand: Metabolomics
  - name: metagenomics
    brand: Metagenomics
  - name: microbiome
    brand: Microbiome
  - name: microgalaxy
    brand: microGalaxy
  - name: rna
    brand: RNA
  - name: graphclust
    brand: GraphClust
  - name: ecology
    brand: Ecology
    custom_css: |
        #masthead {
          background: linear-gradient(to right,#2171b5 0.00%,#2171b5 0.83%,#c6dbef 0.83%,#c6dbef 1.65%,#9ecae1 1.65%,#9ecae1 2.48%,#fee0d2 2.48%,#fee0d2 3.31%,#6baed6 3.31%,#6baed6 4.13%,#9ecae1 4.13%,#9ecae1 4.96%,#08519c 4.96%,#08519c 5.79%,#08306b 5.79%,#08306b 6.61%,#2171b5 6.61%,#2171b5 7.44%,#4292c6 7.44%,#4292c6 8.26%,#9ecae1 8.26%,#9ecae1 9.09%,#2171b5 9.09%,#2171b5 9.92%,#4292c6 9.92%,#4292c6 10.74%,#9ecae1 10.74%,#9ecae1 11.57%,#deebf7 11.57%,#deebf7 12.40%,#9ecae1 12.40%,#9ecae1 13.22%,#deebf7 13.22%,#deebf7 14.05%,#4292c6 14.05%,#4292c6 14.88%,#08519c 14.88%,#08519c 15.70%,#deebf7 15.70%,#deebf7 16.53%,#9ecae1 16.53%,#9ecae1 17.36%,#c6dbef 17.36%,#c6dbef 18.18%,#6baed6 18.18%,#6baed6 19.01%,#4292c6 19.01%,#4292c6 19.83%,#2171b5 19.83%,#2171b5 20.66%,#deebf7 20.66%,#deebf7 21.49%,#fcbba1 21.49%,#fcbba1 22.31%,#9ecae1 22.31%,#9ecae1 23.14%,#deebf7 23.14%,#deebf7 23.97%,#9ecae1 23.97%,#9ecae1 24.79%,#deebf7 24.79%,#deebf7 25.62%,#4292c6 25.62%,#4292c6 26.45%,#deebf7 26.45%,#deebf7 27.27%,#2171b5 27.27%,#2171b5 28.10%,#fee0d2 28.10%,#fee0d2 28.93%,#fcbba1 28.93%,#fcbba1 29.75%,#08519c 29.75%,#08519c 30.58%,#9ecae1 30.58%,#9ecae1 31.40%,#4292c6 31.40%,#4292c6 32.23%,#c6dbef 32.23%,#c6dbef 33.06%,#fee0d2 33.06%,#fee0d2 33.88%,#9ecae1 33.88%,#9ecae1 34.71%,#c6dbef 34.71%,#c6dbef 35.54%,#2171b5 35.54%,#2171b5 36.36%,#fcbba1 36.36%,#fcbba1 37.19%,#4292c6 37.19%,#4292c6 38.02%,#c6dbef 38.02%,#c6dbef 38.84%,#4292c6 38.84%,#4292c6 39.67%,#ef3b2c 39.67%,#ef3b2c 40.50%,#deebf7 40.50%,#deebf7 41.32%,#fee0d2 41.32%,#fee0d2 42.15%,#c6dbef 42.15%,#c6dbef 42.98%,#08306b 42.98%,#08306b 43.80%,#08519c 43.80%,#08519c 44.63%,#2171b5 44.63%,#2171b5 45.45%,#fcbba1 45.45%,#fcbba1 46.28%,#c6dbef 46.28%,#c6dbef 47.11%,#fcbba1 47.11%,#fcbba1 47.93%,#deebf7 47.93%,#deebf7 48.76%,#fcbba1 48.76%,#fcbba1 49.59%,#fc9272 49.59%,#fc9272 50.41%,#fee0d2 50.41%,#fee0d2 51.24%,#9ecae1 51.24%,#9ecae1 52.07%,#fcbba1 52.07%,#fcbba1 52.89%,#6baed6 52.89%,#6baed6 53.72%,#4292c6 53.72%,#4292c6 54.55%,#08306b 54.55%,#08306b 55.37%,#fee0d2 55.37%,#fee0d2 56.20%,#c6dbef 56.20%,#c6dbef 57.02%,#fcbba1 57.02%,#fcbba1 57.85%,#deebf7 57.85%,#deebf7 58.68%,#fcbba1 58.68%,#fcbba1 59.50%,#08519c 59.50%,#08519c 60.33%,#9ecae1 60.33%,#9ecae1 61.16%,#4292c6 61.16%,#4292c6 61.98%,#deebf7 61.98%,#deebf7 62.81%,#fcbba1 62.81%,#fcbba1 63.64%,#9ecae1 63.64%,#9ecae1 64.46%,#6baed6 64.46%,#6baed6 65.29%,#deebf7 65.29%,#deebf7 66.12%,#6baed6 66.12%,#6baed6 66.94%,#c6dbef 66.94%,#c6dbef 67.77%,#fcbba1 67.77%,#fcbba1 68.60%,#deebf7 68.60%,#deebf7 69.42%,#fee0d2 69.42%,#fee0d2 70.25%,#6baed6 70.25%,#6baed6 71.07%,#4292c6 71.07%,#4292c6 71.90%,#c6dbef 71.90%,#c6dbef 72.73%,#fcbba1 72.73%,#fcbba1 73.55%,#9ecae1 73.55%,#9ecae1 74.38%,#2171b5 74.38%,#2171b5 75.21%,#9ecae1 75.21%,#9ecae1 76.03%,#2171b5 76.03%,#2171b5 76.86%,#fc9272 76.86%,#fc9272 77.69%,#ef3b2c 77.69%,#ef3b2c 78.51%,#c6dbef 78.51%,#c6dbef 79.34%,#fb6a4a 79.34%,#fb6a4a 80.17%,#deebf7 80.17%,#deebf7 80.99%,#cb181d 80.99%,#cb181d 81.82%,#fcbba1 81.82%,#fcbba1 82.64%,#08519c 82.64%,#08519c 83.47%,#fcbba1 83.47%,#fcbba1 84.30%,#fc9272 84.30%,#fc9272 85.12%,#ef3b2c 85.12%,#ef3b2c 85.95%,#cb181d 85.95%,#cb181d 86.78%,#fcbba1 86.78%,#fcbba1 87.60%,#ef3b2c 87.60%,#ef3b2c 88.43%,#fb6a4a 88.43%,#fb6a4a 89.26%,#fcbba1 89.26%,#fcbba1 90.08%,#ef3b2c 90.08%,#ef3b2c 90.91%,#cb181d 90.91%,#cb181d 91.74%,#ef3b2c 91.74%,#ef3b2c 92.56%,#fc9272 92.56%,#fc9272 93.39%,#6baed6 93.39%,#6baed6 94.21%,#ef3b2c 94.21%,#ef3b2c 95.04%,#fc9272 95.04%,#fc9272 95.87%,#fee0d2 95.87%,#fee0d2 96.69%,#67000d 96.69%,#67000d 97.52%,#cb181d 97.52%,#cb181d 98.35%,#ef3b2c 98.35%,#ef3b2c 99.17%,#67000d 99.17%,#67000d 100.00%);
        }
        #masthead .navbar-brand {
          background: #3337;
          height: 100%;
          padding: 0.5em;
          left: 0px;
        }
        #masthead .navbar-nav > li .nav-link {
            color: white;
        }
        #masthead .navbar-nav > li {
            background: #3337;
        }
        #masthead .navbar-nav > li.active {
            background: #333e;
        }
  - name: proteomics
    brand: Proteomics
  - name: clipseq
    brand: CLIP-Explorer
  - name: cheminformatics
    brand: Cheminformatics
  - name: imaging
    brand: Imaging
    custom_css: |
        #masthead {
            background: linear-gradient(90deg, rgb(0, 0, 0) 0%, rgb(0, 69, 227) 17%, rgb(9, 121, 33) 30%, rgb(180, 170, 15) 70%, rgb(193, 35, 0) 79%, rgb(0, 0, 0) 100%);
        }
  - name: test
    brand: Testing
    domain: test.internal.usegalaxy.eu
    custom_css: |
        #masthead {
            background: linear-gradient(to bottom,#e2453c 0,#e2453c 16%,#e07e39 16%,#e07e39 32%,#e5d667 32%,#e5d667 48%,#51b95b 48%,#51b95b 66%,#1e72b7 66%,#1e72b7 86%,#6f5ba7 86%) no-repeat;
        }
        #masthead .navbar-brand {
          background: #3337;
          height: 100%;
          padding: 0.5em;
          left: 0px;
        }
        #masthead .navbar-nav > li .nav-link {
            color: white;
        }
        #masthead .navbar-nav > li {
            background: #3337;
        }
        #masthead .navbar-nav > li.active {
            background: #333e;
        }
  - name: beta
    brand: Europe
  - name: streetscience
    brand: StreetScienceCommunity
  - name: singlecell
    brand: Single Cell Omics
  - name: humancellatlas
    brand: Human Cell Atlas
  - name: ml
    brand: Machine Learning
  - name: live
    brand: Live
    domain: live.usegalaxy.eu
    custom_css: |
        #left{
            display: none !important;
        }
        #center{
            left: 0px !important;
        }
        #masthead {
            background: linear-gradient(33deg, rgba(131,58,180,1) 0%, rgba(253,29,29,1) 25%, rgba(252,176,69,1) 50%, rgba(253,29,29,1) 75%, rgba(131,58,180,1) 100%);
            -webkit-animation: SuperLively 20s ease infinite;
            -moz-animation: SuperLively 20s ease infinite;
            animation: SuperLively 20s ease infinite;
            background-size: 600% 600%;
        }
        @-webkit-keyframes SuperLively {
            0%{background-position:0% 51%}
            50%{background-position:100% 50%}
            100%{background-position:0% 51%}
        }
        @-moz-keyframes SuperLively {
            0%{background-position:0% 51%}
            50%{background-position:100% 50%}
            100%{background-position:0% 51%}
        }
        @keyframes SuperLively {
            0%{background-position:0% 51%}
            50%{background-position:100% 50%}
            100%{background-position:0% 51%}
        }
  - name: plants
    brand: Plants
    custom_css: |
        #masthead {
            background: linear-gradient(90deg, #1a5d1a 0%, #369c36 50%, rgb(29 95 28) 100%);
        }
  - name: virology
    brand: Virology
  - name: lite
    brand: Lite
  - name: covid19
    brand: COVID-19
  - name: africa
    brand: Africa
  - name: india
    brand: India
  - name: spatialomics
    brand: Spatial Omics
  - name: materials
    brand: Materials
  - name: phage
    brand: Phage
