# Autofs
usegalaxy_eu_autofs_mounts:
 - data

data_conf:
  - jwd     -rw,hard,nosuid      denbi.svm.bwsfs.uni-freiburg.de:/ws01/&

# GALAXY
galaxy_group:
  name: galaxy
  gid: 999
galaxy_system_group: galaxy
galaxy_user:
    name: galaxy
    create_home: true
    home: /opt/galaxy
    uid: 999
    shell: /bin/bash

galaxy_config:
  galaxy:
    ftp_upload_dir: /data/jwd/incoming


# Certbot
server_names:
  - 'ftp.usegalaxy.eu'
  - 'incoming.galaxyproject.eu'
certbot_auto_renew_hour: "{{ 23 |random(seed=inventory_hostname)  }}"
certbot_auto_renew_minute: "{{ 59 |random(seed=inventory_hostname)  }}"
certbot_auth_method: --webroot
certbot_install_method: virtualenv
certbot_auto_renew: yes
certbot_auto_renew_user: root
certbot_well_known_root: /srv/nginx/_well-known_root
certbot_share_key_users:
  - nginx
  - proftpd
certbot_post_renewal: |
    systemctl restart proftpd || true
certbot_domains: "{{ server_names }}"
certbot_agree_tos: --agree-tos
certbot_virtualenv_package_name: python3-virtualenv

# NGINX
nginx_selinux_allow_local_connections: true
nginx_servers:
  - redirect-ssl
nginx_ssl_servers:
  - ftp
nginx_enable_default_server: false
nginx_ssl_role: usegalaxy-eu.certbot
nginx_conf_ssl_certificate: /etc/ssl/certs/fullchain.pem
nginx_conf_ssl_certificate_key: /etc/ssl/user/privkey-nginx.pem
   

# Proftpd:
proftpd_galaxy_auth: yes
galaxy_ftp_upload_dir: "{{ galaxy_config.galaxy.ftp_upload_dir }}"
proftpd_display_connect: |
  {{ inventory_hostname }} FTP server

  Unauthorized access is prohibited
proftpd_options:
  - User: galaxy
  - Group: galaxy
  - Port: 21
proftpd_sql_db: "{{ proftpd__galaxy_db_connection }}"
proftpd_sql_user: ''
proftpd_conf_ssl_certificate: /etc/ssl/certs/cert.pem
proftpd_conf_ssl_certificate_key: /etc/ssl/user/privkey-proftpd.pem
proftpd_conf_ssl_ca_certificate: /etc/letsencrypt/live/ftp.usegalaxy.eu/chain.pem
proftpd_global_options:
  - PassivePorts: 56000 60000
proftpd_use_mod_tls_shmcache: false
proftpd_tls_options: NoSessionReuseRequired
