---
# Certbot
certbot_auth_method: --webroot
certbot_well_known_root: /srv/nginx/_well-known_root
certbot_share_key_users:
  - nginx
  - rabbitmq

certbot_post_renewal: |
    systemctl restart nginx || true
    systemctl restart rabbitmq-server || true

# NGINX
nginx_enable_default_server: false
nginx_servers:
  - proxy-internal
nginx_ssl_servers:
  - proxy-internal-ssl
nginx_conf_http:
  client_max_body_size: 1g
nginx_remove_default_vhost: true

# Nginx Letsencrypt bindings
nginx_ssl_role: usegalaxy-eu.certbot
nginx_conf_ssl_certificate: /etc/ssl/certs/fullchain.pem
nginx_conf_ssl_certificate_key: /etc/ssl/user/privkey-nginx.pem


telegraf_plugins_extra:
  rabbitmq:
    plugin: rabbitmq
    config:
      - url = "http://localhost:15672"
      - username = "telegraf"
      - password = "{{ rabbitmq_password_telegraf }}"

rabbitmq_users:
  - user: admin
    password: "{{ rabbitmq_password_admin }}"
    tags: administrator
    vhost: /
  - user: telegraf
    password: "{{ rabbitmq_password_telegraf }}"
    tags: administrator
    vhost: /
  - user: galaxy
    password: "{{ rabbitmq_password_galaxy }}"
    vhost: galaxy
  - user: galaxy_cz
    password: "{{ rabbitmq_password_galaxy_cz }}"
    vhost: /pulsar/galaxy_cz
  - user: galaxy_test
    password: "{{ rabbitmq_password_galaxy_test }}"
    vhost: /pulsar/galaxy_test
  - user: vgcn_test
    password: "{{ rabbitmq_password_galaxy_vgcn }}"
    vhost: /pulsar/galaxy_vgcn
  - user: galaxy_be01
    password: "{{ rabbitmq_password_galaxy_be01 }}"
    vhost: /pulsar/galaxy_be01
  - user: galaxy_it01
    password: "{{ rabbitmq_password_galaxy_it01 }}"
    vhost: /pulsar/galaxy_it01
  - user: galaxy_de01
    password: "{{ rabbitmq_password_galaxy_de01 }}"
    vhost: /pulsar/galaxy_de01
  - user: galaxy_de02
    password: "{{ rabbitmq_password_galaxy_de02 }}"
    vhost: /pulsar/galaxy_de02
  - user: galaxy_de03
    password: "{{ rabbitmq_password_galaxy_de03 }}"
    vhost: /pulsar/galaxy_de03
  - user: galaxy_pt01
    password: "{{ rabbitmq_password_galaxy_pt01 }}"
    vhost: /pulsar/galaxy_pt01
  - user: galaxy_uk01
    password: "{{ rabbitmq_password_galaxy_uk01 }}"
    vhost: /pulsar/galaxy_uk01
  - user: galaxy_au01
    password: "{{ rabbitmq_password_galaxy_au01 }}"
    vhost: /pulsar/galaxy_au01
  - user: galaxy_no01
    password: "{{ rabbitmq_password_galaxy_no01 }}"
    vhost: /pulsar/galaxy_no01
  - user: galaxy_it02
    password: "{{ rabbitmq_password_galaxy_it02 }}"
    vhost: /pulsar/galaxy_it02

rabbitmq_vhosts:
  - galaxy
  - /pulsar/galaxy_it01
  - /pulsar/galaxy_be01
  - /pulsar/galaxy_cz
  - /pulsar/galaxy_de01
  - /pulsar/galaxy_de02
  - /pulsar/galaxy_de03
  - /pulsar/galaxy_test
  - /pulsar/galaxy_vgcn
  - /pulsar/galaxy_pt01
  - /pulsar/galaxy_uk01
  - /pulsar/galaxy_au01
  - /pulsar/galaxy_no01
  - /pulsar/galaxy_it02
  
rabbitmq_plugins:
  - rabbitmq_management

rabbitmq_config:
- rabbit:
  #- tcp_listeners:
    #- "'0.0.0.0'": 5671
  - ssl_listeners:
    - "'0.0.0.0'": 5671
  - ssl_options:
    - cacertfile: /etc/ssl/certs/fullchain.pem
    - certfile: /etc/ssl/certs/cert.pem
    - keyfile: /etc/ssl/user/privkey-rabbitmq.pem
    - fail_if_no_peer_cert: 'false'
