---
# create_user task
user_name: galaxy
user_uid: 999
user_comment: Tusd Service-Acct
user_group_name: galaxy
user_gid: 999

# Autofs
autofs_service.install: true
autofs_service.enable: true
nfs_kernel_tuning: true

autofs_mount_points:
    - data
    - gxtest
    - gxkey
    - jwd

# usegalaxy_eu.handy.os_setup
## packages
software_groups_to_install:
    - editors
    - utils

## kernel_5
kernel_5_package: kernel-ml
