---
rustus_version: "0.7.4"
rustus_instances:
  - name: test_uploads
    # user that rustus will run as
    user: "{{ user_name }}"
    # group that rustus will run as
    group: "{{ user_group_name }}"
    # by default, rustus will refuse to work if it cannot write to its current working
    # directory, read the documentation of the usegalaxy_eu.rustus role for more
    # details
    working_directory: "{{ upload_dir_test }}"
    # args passed to rustus
    args:
      - --host "{{ inventory_hostname }}"
      - --port 1080
      - "--data-dir {{ upload_dir_test }}"
      - --hooks-http-urls "https://test.usegalaxy.eu/api/upload/hooks"
      - --hooks-http-proxy-headers "X-Api-Key,Cookie"
      - --hooks "pre-create"
      - --hooks-format tusd
      - --url "/api/upload/resumable_upload"
      - --max-body-size 20000000
      - "--sentry-dsn {{ sentry_dsn.test }} --sentry-sample-rate 1.0"
      - --info-storage "file-info-storage" --info-dir "{{ upload_dir_test }}"
  - name: main_uploads
    # user that rustus will run as
    user: "{{ user_name }}"
    # group that rustus will run as
    group: "{{ user_group_name }}"
    # by default, rustus will refuse to work if it cannot write to its current working
    # directory, read the documentation of the usegalaxy_eu.rustus role for more
    # details
    working_directory: "{{ upload_dir_main }}"
    # args passed to rustus
    args:
      - --host "{{ inventory_hostname }}"
      - --port 1081
      - "--data-dir {{ upload_dir_main }}"
      - --hooks-http-urls "https://usegalaxy.eu/api/upload/hooks"
      - --hooks-http-proxy-headers "X-Api-Key,Cookie"
      - --hooks "pre-create"
      - --hooks-format tusd
      - --url "/api/upload/resumable_upload"
      - --max-body-size 20000000
      - "--sentry-dsn {{ sentry_dsn.main }} --sentry-sample-rate 1.0"
      - --info-storage "file-info-storage" --info-dir "{{ upload_dir_main }}"
user_name: galaxy
user_group_name: galaxy

# create_user task
handy_groups:
  - group_name: "{{ user_group_name }}"
    group_gid: 999

handy_users:
  - user_name: "{{ user_name }}"
    user_uid: 999
    user_comment: rustus Service-Acct
    user_group: "{{ user_group_name }}"

# Autofs
autofs_service:
  install: true
  enable: true
nfs_kernel_tuning: true

autofs_mount_points:
  - data
  - gxtest
  - gxkey
  - jwd

# usegalaxy_eu.handy.os_setup
## packages
software_groups_to_install:
  - editors
  - utils

## kernel_5
kernel_5_package: kernel-ml
