---
dependencies: []
galaxy_info:
  role_name: yum_cron
  author: tkimball83
  description: RHEL/CentOS - An interface to conveniently call yum from cron
  license: GPLv3
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - 6
        - 7
  galaxy_tags:
    - yum
...
