- name: Set multisite dir to a subdirectory of mutable data dir
  set_fact:
    multisite_dir: "/opt/multisite-css"

- name: Create directory
  file:
    path: "{{ multisite_dir }}"
    state: directory
    mode: 0755

- name: Template out main welcome page
  template:
    src: welcome.html
    dest: "{{ multisite_dir }}/usegalaxy.eu.html"
    mode: 0644
  with_items:
    - index: "/galaxy/"

- name: "Template out welcome pages"
  template:
    src: welcome.html
    dest: "{{ multisite_dir }}/{{ item.domain | default([item.name, '.usegalaxy.eu'] | join) }}.html"
    mode: 0644
  with_items: "{{ galaxy_custom_sites }}"

- name: Template out CSS files
  template:
    src: multisite-base.css
    dest: "{{ multisite_dir }}/{{ item.domain | default([item.name, '.usegalaxy.eu'] | join) }}-custom.css"
    mode: 0644
  with_items: "{{ galaxy_custom_sites }}"
  register: custom_css

- name: Template out CSS files
  copy:
    dest: "{{ multisite_dir }}/usegalaxy.eu-custom.css"
    content: "{{ galaxy_custom_site_base_css }}"
    mode: 0644
  when: galaxy_custom_site_base_css is defined
  register: base_css

- name: Copy custom background images
  copy:
    src: "files/welcome-sites/{{ item.name }}.png"
    dest: "{{ multisite_dir }}/{{ item.name }}.png"
    mode: 0644
  with_items: "{{ galaxy_custom_sites }}"
  when: item.wallpaper | default(False)

- name: Main CSS
  shell: "cat {{ galaxy_server_dir }}/static/style/base.css {% if galaxy_custom_site_base_css is defined %}{{ multisite_dir }}/usegalaxy.eu-custom.css {% endif %} > {{ multisite_dir }}/usegalaxy.eu.css"
  when: __galaxy_git_update_result is changed or (galaxy_custom_site_base_css is defined and base_css is changed)

- name: Main CSS replace background color
  replace:
    path: "{{ multisite_dir }}/usegalaxy.eu.css"
    regexp: '#masthead{background-color:#2c3143}'
    replace: '#masthead{background-color:#003399}'

- name: Merge CSS files
  shell: "cat {{ galaxy_server_dir }}/static/style/base.css {{ multisite_dir }}/{{ item.domain | default([item.name, '.usegalaxy.eu'] | join) }}-custom.css > {{ multisite_dir }}/{{ item.domain | default([item.name, '.usegalaxy.eu'] | join) }}.css"
  with_items: "{{ galaxy_custom_sites }}"
  when: __galaxy_git_update_result is changed or custom_css is changed
