---
bashrc_users:
  - uname: "{{ galaxy_user.name }}"
    uhome: "{{ galaxy_user.home }}"
    gname: "{{ galaxy_group.name }}"

bashrc_galaxy_job_working_directory: "{{ undef() }}"
bashrc_galaxy_config_dir: "{{ undef() }}"
bashrc_galaxy_config_file: "{{ undef() }}"
bashrc_galaxy_log_dir: "{{ undef() }}"
bashrc_galaxy_mutable_config_dir: "{{ undef() }}"
bashrc_galaxy_root: "{{ undef() }}"
bashrc_galaxy_venv_dir: "{{ undef() }}"
bashrc_galaxy_pulsar_app_conf: "{{ undef() }}"
