sleep_duration: 240
cron_tasks:
  - name: "Call sync-to-nfs"
    minute: 30
    hour: 2
    job: "/usr/bin/galaxy-sync-to-nfs"
    user: galaxy
  - name: "Restart handlers"
    minute: 0
    hour: 3
    job: "/bin/bash -c 'for (( c=0; c<{{ galaxy_systemd_handlers }}; c++ )); do systemctl restart galaxy-handler@$c && sleep {{ sleep_duration }}; done'"
    user: root
  - name: "Restart gunicorn"
    minute: 30
    hour: 3
    job: "/bin/bash -c 'for (( c=0; c<{{ galaxy_systemd_gunicorns }}; c++ )); do systemctl restart galaxy-gunicorn@$c && sleep {{ sleep_duration }}; done'"
    user: root
  - name: "Restart workflow schedulers"
    minute: 0
    hour: 4
    job: "/bin/bash -c 'for (( c=0; c<{{ galaxy_systemd_workflow_schedulers }}; c++ )); do systemctl restart galaxy-workflow-scheduler@$c && sleep {{ sleep_duration }}; done'"
    user: root
