---

- name: Install CernVM-FS client (yum)
  yum:
    name: cvmfs
  when: ansible_os_family == "RedHat"

- name: Install CernVM-FS client (apt)
  apt:
    name: cvmfs
  when: ansible_os_family == "Debian"

- name: Install CernVM-FS keys
  copy:
    content: "{{ item.key }}"
    dest: "{{ item.path }}"
    owner: "root"
    group: "root"
    mode: "0444"
  with_items: "{{ cvmfs_keys }}"

- name: Perform AutoFS and FUSE configuration for CernVM-FS
  command: cvmfs_config setup
  notify:
    - reload autofs

- name: Configure CernVM-FS domain
  copy:
    content: |
      CVMFS_SERVER_URL="{{ item.urls | join(';') }}"
    dest: "/etc/cvmfs/domain.d/{{ item.domain }}.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{ cvmfs_server_urls }}"

- name: Configure CernVM-FS client settings
  copy:
    content: |
      CVMFS_REPOSITORIES="{%- for repo in cvmfs_repositories -%}{{ ',' if loop.index0 > 0 else '' }}{{ repo.repository }}{%- endfor -%}"
      CVMFS_HTTP_PROXY="{{ cvmfs_http_proxies | join(';') }}"
      CVMFS_QUOTA_LIMIT="{{ cvmfs_quota_limit | default('4000') }}"
    dest: "/etc/cvmfs/default.local"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Install cvmfs_wipecache setuid binary
  copy:
    src: cvmfs_wipecache.{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}
    dest: /usr/local/bin/cvmfs_wipecache
    owner: root
    group: root
    mode: 06755
  when: cvmfs_install_setuid_cvmfs_wipecache
