---
- name: "Deploy fixer upper script"
  copy:
    content: |
        #!/bin/bash
        cd {{ galaxy_server_dir }}
        . {{ galaxy_root }}/.bashrc
        python scripts/set_user_disk_usage.py -c {{ galaxy_config_file }}
    dest: /usr/bin/galaxy-fix-user-quotas
    owner: root
    group: root
    mode: 0755

- name: Add to cron
  cron:
    name: "Fix user quotas"
    minute: 15
    hour: 22
    job: /usr/bin/galaxy-fix-user-quotas
    user: galaxy
