---

group_packages:
  - git
  - tmpwatch
  # Pulsar deps
  - '@development tools'
  - python-virtualenv
  - libffi-devel
  - libcurl-devel
  - nss-devel
  - openssl-devel
  - slurm-drmaa

group_files:
  - src: files/etc/dhclient.conf
    dest: /etc/dhcp/dhclient.conf
    backup: yes
    mode: "0644"
    owner: root
    group: root
  - src: files/etc/ifcfg-eth1
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    backup: yes
    mode: "0644"
    owner: root
    group: root

jetstream_scratch0_device: /dev/sdb

directories:
  - path: /jetstream
  - path: /var/lib/slurm
    mode: "0755"
  - path: /srv/pulsar/test
    owner: g2test
    group: G-803372
  - path: /srv/pulsar/test/pulsar/log
    owner: g2test
    group: G-803372
  - path: /srv/pulsar/main
    owner: g2main
    group: G-803372
  - path: /srv/pulsar/main/pulsar/log
    owner: g2main
    group: G-803372

links:
  - path: /jetstream/scratch0
    src: /scratch0
    force: yes

supervisord_install: package
supervisord_group_configs:
  - pulsar

crontabs:
  - id: clean_scratch
    name: Clean Test Scratch
    user: g2test
    minute: 05,20,35,50
    job: /usr/bin/tmpwatch --mtime --dirmtime 4d /scratch0/test/jobs
  - id: clean_scratch
    name: Clean Main Scratch
    user: g2main
    minute: 00,15,30,45
    job: /usr/bin/tmpwatch --mtime --dirmtime 4d /scratch0/main/jobs
