---

group_packages:
  - '@development'
  - python-virtualenv
  - python-psycopg2
  # sentry deps
  - memcached
  - postgresql95-devel
  - libxml2-devel
  - libxslt-devel
  - libffi-devel
  - openssl-devel

postgresql_version: '9.5'

postgresql_objects_users: 
  - name: sentry
  - name: graphite

postgresql_objects_databases:
  - name: sentry
    owner: sentry
  - name: graphite
    owner: graphite

supervisord_install: package

supervisord_group_configs:
  - sentry
  - stats

# used in the nginx template, which is run in a play that does not include the
# sentry role
sentry_sock_dir: /var/run/sentry
