---
- name: Enable nginx repo.
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644
  when: nginx_yum_repo_enabled

- name: Ensure nginx is installed.
  yum:
    name: "{{ nginx_package_name }}"
    state: installed


- name: check if selinux is enabled
  tags: selinuxCheck
  register: selinuxCheckOut
  command: getenforce




- name: "Allow connecting to localhost"
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: selinuxCheckOut.stdout_lines == "Enforcing"
