---

- name: Tasks for "base environment" hosts
  hosts: baseenv
  remote_user: root
  vars_files:
    #- "secret_group_vars/all.yml"
    # uncomment when necessary
    - [ "secret_host_vars/{{ inventory_hostname }}.yml", "secret_host_vars/default.yml" ]
  pre_tasks:
    - name: Locate secret group variable files
      local_action:
        module: stat
        path: "{{ inventory_dir }}/secret_group_vars/{{ item }}.yml"
      with_items: "{{ group_names }}"
      register: secret_group_vars
      tags: always
    - name: Include secret group variables
      local_action:
        module: "include_vars {{ item.stat.path }}"
      with_items: "{{ secret_group_vars.results }}"
      when: item.stat.exists
      tags: always
  roles:
    - role: packages          # Install packages
      tags: system,packages
    - role: users             # Create users and set up authentication keys
      tags: system,users
    - role: paths             # Configure path permissions, filesystems
      tags: system,paths
    - role: copy              # Copy arbitrary files/templates
      tags: system,copy
    - role: cron              # Create cron jobs
      tags: system,cron
    - role: services          # Manage services
      tags: system,services
  tags: initial

- name: Forward mail for local accounts
  hosts: all
  remote_user: root
  tasks:
    - name: Forward mail for {{ item }}
      lineinfile:
        dest: /etc/aliases
        regexp: "^{{ item }}:"
        line: "{{ item }}:	root@galaxyproject.org"
      with_items:
        - g2test
        - g2main
        - postgres
      notify: run newaliases
  handlers:
    - name: run newaliases
      command: /usr/bin/newaliases
  tags: system

- name: Tasks for webservers
  hosts: webservers
  remote_user: root
  vars_files:
    - secret_group_vars/sslwebservers.yml
  roles:
    - role: geerlingguy.repo-epel
    - role: galaxyprojectdotorg.nginx
  tags: nginx

- name: Tasks for stats servers
  hosts: statsservers
  remote_user: root
  vars_files:
    - secret_group_vars/stats.yml
  roles:
    - role: galaxyprojectdotorg.postgresql
      tags: postgres
    - role: sentry
      tags: sentry
    - role: stats
      tags: stats
    - role: supervisor
      tags: supervisor

- name: Database tasks for stats servers
  hosts: statsservers
  remote_user: root
  become: yes
  become_method: sudo
  become_user: postgres
  roles:
    - role: natefoo.postgresql_objects
      tags: postgres

- name: Tasks for CVMFS clients
  hosts: cvmfsclients
  remote_user: root
  roles:
    - role: geerlingguy.repo-epel
    - role: cvmfs
  tags: cvmfs

- name: Tasks for slurm hosts
  hosts: slurmservers:slurmclients
  remote_user: root
  vars_files:
    - secret_group_vars/slurmclients.yml
  roles:
    - role: slurm
  tags: slurm

- name: Tasks for docker clients
  hosts: dockerclients
  remote_user: root
  roles:
    - role: docker
  tags: docker
