---

# 100 GB
cvmfs_quota_limit: 100000

group_packages:
  - collectl
  - lzo

directories:
  - path: /galaxy-repl/test
  - path: /galaxy-repl/main
  - path: /var/lib/slurm
    mode: "0755"

# symlinks for deps must exist due to path issues
links:
  - path: /galaxy
    src: /galaxy-repl
    force: yes
  - path: /galaxy-repl/test/deps
    src: /cvmfs/test.galaxyproject.org/deps
    force: yes
  - path: /galaxy-repl/test/tool_data
    src: /cvmfs/data.galaxyproject.org/byhand/location
    force: yes
  - path: /galaxy-repl/main/deps
    src: /cvmfs/main.galaxyproject.org/deps
    force: yes
  - path: /galaxy-repl/main/tool_data
    src: /cvmfs/data.galaxyproject.org/byhand/location
    force: yes

jetstream_nfs_filesystems:
  - device: "10.0.0.9:/scratch0"
    dir: scratch0
    mountpoint: /jetstream/tacc-scratch0
