---
galaxy_info:
  author: z
  description: Tomcat 7 for RHEL/CentOS.
  company:
  license: license (BSD, MIT)
  min_ansible_version: 1.9
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - web
dependencies: []
