---
- name: Copy server key into VM temporarily
  copy:
    src: server_ca
    dest: /tmp/server_ca
    owner: root
    group: root
    mode: 0600

- name: Sign Keys
  command: ssh-keygen -s /tmp/server_ca -I key_for_test1 -h -V +520w /etc/ssh/ssh_host_{{ item }}_key.pub
  with_items:
    - rsa
    - ecdsa
    - ed25519
  # This ensures the server_ca will be removed in any case
  ignore_errors: true

- name: Ensure server key is gone
  file:
    path: /tmp/server_ca
    state: absent

- name: Add keys to SSHD Config
  ansible.builtin.lineinfile:
    line: "{{ item }}"
    path: /etc/ssh/sshd_config
  with_items:
    - HostCertificate /etc/ssh/ssh_host_rsa_key-cert.pub
    - HostCertificate /etc/ssh/ssh_host_ecdsa_key-cert.pub
    - HostCertificate /etc/ssh/ssh_host_ed25519_key-cert.pub
  notify: "restart sshd"

- name: "Helper"
  debug:
    msg: "Please add the following to your known_hosts file: @cert-authority {{ ssh_host_resign_cert_domains_ips }} {{ lookup('file', 'server_ca.pub')  }}"
