ssh_manager_authorized_persons: "{{ ssh_manager_authorized_persons_vault }}"

ssh_host_resign_cert_domains_ips: "*.galaxyproject.eu,*.usegalaxy.eu,*.bi.privat,192.52.33.*,192.52.32.*,10.4.68.*,10.5.68.*,10.5.67.*"
