---
ssh_manager_authorized_persons:
  cloud:  # Not an actual person. This user powers automations.
    key: "{{ ssh_manager_authorized_persons_vault.cloud }}"
    machines: all
    users:
      - root
      - operator
      - rocky
      - centos
      - galaxy
      - stats

  jenkins:  # Not an actual person. This user powers automations.
    key: "{{ ssh_manager_authorized_persons_vault.jenkins }}"
    machines: build-workers
    users:
      - root
      - operator

  #galaxy:  # Not an actual person. This user powers automations.
  #  key:
  #    - "{{ galaxy_user_public_key }}"
  #  machines:
  #    - sn09.galaxyproject.eu
  #  users:
  #    - galaxy
  # `galaxy_user_public_key` is not defined

  bgruening:
    key: "{{ ssh_manager_authorized_persons_vault.bgruening }}"
    machines: all
    users:
      - root
      - operator
      - rocky
      - centos
      - galaxy
      - stats

  mira-miracoli:
    key: "{{ ssh_manager_authorized_persons_vault['mira-miracoli'] }}"
    machines:
      - all
    users:
      - root
      - operator
      - rocky
      - centos
      - galaxy
      - stats

  kysrpex:
    key: "{{ ssh_manager_authorized_persons_vault.kysrpex }}"
    machines:
      - all
    users:
      - root
      - operator
      - rocky
      - centos
      - galaxy
      - stats

  gsaudade99:
    key: "{{ ssh_manager_authorized_persons_vault.gsaudade99 }}"
    machines:
      - all
    users:
      - root
      - operator
      - rocky
      - centos
      - galaxy
      - stats

  bernd:
    key: "{{ ssh_manager_authorized_persons_vault.bernd }}"
    machines:
      - sn11.galaxyproject.eu
      - sn12.galaxyproject.eu
    users:
      - root
      - operator

  wm75:
    key: "{{ ssh_manager_authorized_persons_vault.wm75 }}"
    machines:
      - sn09.galaxyproject.eu
    users:
      - galaxy
      - stats

  videmp:
    key: "{{ ssh_manager_authorized_persons_vault.videmp }}"
    machines:
      - sn09.galaxyproject.eu
    users:
      - stats

  paul:
    key: "{{ ssh_manager_authorized_persons_vault.paul }}"
    machines:
      - sn09.galaxyproject.eu
    users:
      - stats

  davelopez:
    key: "{{ ssh_manager_authorized_persons_vault.davelopez }}"
    machines:
      - sn09.galaxyproject.eu
    users:
      - stats

  natefoo:
    key: "{{ ssh_manager_authorized_persons_vault.natefoo }}"
    machines:
      - sn09.galaxyproject.eu
    users:
      - stats
      - galaxy

  bebatut:
    key: "{{ ssh_manager_authorized_persons_vault.bebatut }}"
    machines:
      - sn09.galaxyproject.eu
    users:
      - stats

  jdavcs:
    key: "{{ ssh_manager_authorized_persons_vault.jdavcs }}"
    machines:
      - sn09.galaxyproject.eu
    users:
      - stats

  mvdbeek:
    key: "{{ ssh_manager_authorized_persons_vault.mvdbeek }}"
    machines:
      - sn09.galaxyproject.eu
    users:
      - stats

  cat-bro:
    key: "{{ ssh_manager_authorized_persons_vault['cat-bro'] }}"
    machines:
      - sn09.galaxyproject.eu
    users:
      - stats

  abretaud:
    key: "{{ ssh_manager_authorized_persons_vault.abretaud }}"
    machines: sn09.galaxyproject.eu
    users:
      - galaxy
