---

nginx_conf_ssl_certificate: /etc/nginx/ssl/wildcard_cert.pem
nginx_conf_ssl_certificate_key: /etc/nginx/ssl/wildcard_privatekey.pem

nginx_configs:
  - graphite
  - sentry

nginx_default_redirect_uri: https://sentry.galaxyproject.org/

local_users:
  - name: sentry
    #group: sentry # this happens automatically if unset
    groups: nginx
    comment: 'Sentry'
    system: yes
    home: /var/opt/sentry
    createhome: yes
    shell: /bin/bash
