---
# geerlingguy.repo-epel role doesn't enable PowerTools repository
# but EPEL packages may depend on packages from it
- name: Enable CentOS PowerTools repository
  ini_file:
    path: "{{ CentOS.path }}"
    section: "{{ CentOS.section }}"
    option: enabled
    value: "1"
    no_extra_spaces: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_version in CentOS.version

- name: Enable CentOS-Linux PowerTools repository
  ini_file:
    path: "{{ CentOS_Linux.path }}"
    section: "{{ CentOS_Linux.section }}"
    option: enabled
    value: "1"
    no_extra_spaces: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_version in CentOS_Linux.version
