---
- name: "Install simple-ssl-check script"
  copy:
    src: simple-ssl-check.sh
    dest: /usr/bin/simple-ssl-check
    owner: root
    group: root
    mode: 0755

- set_fact:
    plugin_config_monitor_ssl:
      ssl_expiry:
        plugin: "exec"
        config:
          - commands = ["/usr/bin/simple-ssl-check {{ hxr_monitor_ssl_expiry | join(',') }}"]
          - timeout = "15s"
          - data_format = "influx"
          - interval = "15m"

- set_fact:
    telegraf_plugins_extra: "{{ telegraf_plugins_extra | combine(plugin_config_monitor_ssl) }}"
