data_conf:
  - 0       -rw,hard,nosuid,quota      sn01.bi.uni-freiburg.de:/export/data3/galaxy/net/data/&
  - 1       -rw,hard,nosuid,quota      sn03.bi.uni-freiburg.de:/export/galaxy1/data/&
  - 2       -rw,hard,nosuid,quota      sn01.bi.uni-freiburg.de:/export/data4/galaxy/net/data/&
  - 3       -rw,hard,nosuid,quota      sn01.bi.uni-freiburg.de:/export/data5/galaxy/net/data/&
  - 4       -rw,hard,nosuid,quota      sn03.bi.uni-freiburg.de:/export/galaxy1/data/&
  - 5       -rw,hard,nosuid,quota      sn03.bi.uni-freiburg.de:/export/galaxy1/data/&
  - 6       -rw,hard,nosuid,quota      sn03.bi.uni-freiburg.de:/export/galaxy1/data/&
  - 7       -rw,hard,nosuid,quota      sn03.bi.uni-freiburg.de:/export/galaxy1/data/&
  - dnb01   -rw,hard,nosuid,quota      ufr.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
  - dnb02   -rw,hard,nosuid,quota      ufr.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
  - dnb03   -rw,hard,nosuid,quota      ufr.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
  - dnb04   -rw,hard,nosuid,quota      ufr.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
  - db      -rw,hard,nosuid,quota      ufr.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
  - jwd     -rw,hard,nosuid,quota      ufr.isi1.public.ads.uni-freiburg.de:/ifs/isi1/ufr/bronze/nfs/denbi/&
  - gxmnt   -rw,hard,nosuid,quota      sn03.bi.uni-freiburg.de:/export/galaxy1/system/galaxy
  - gxnew   -rw,hard,nosuid,quota      sn03.bi.uni-freiburg.de:/export/galaxy1/system/galaxy-i1
  - gxtst   -rw,hard,nosuid,quota      sn03.bi.uni-freiburg.de:/export/galaxy1/system/galaxy-i2
  - gxkey   -rw,hard,nosuid,quota      sn03.bi.uni-freiburg.de:/export/galaxy1/system/galaxy-i3

discontinued_conf:
  - db      -rw,hard,nosuid,quota      sn02.bi.uni-freiburg.de:/export/fdata1/galaxy/net/data/db

usrlocal_conf:
  - /usr/local/galaxy  -rw,hard,nosuid,quota       sn03.bi.uni-freiburg.de:/export/galaxy1/system/galaxy
  - /usr/local/tools   -rw,hard,nosuid,quota       sn03.bi.uni-freiburg.de:/export/galaxy1/system/tools