---
# Example:
# galaxy_cleanup_objectstores:
#   - objectstore_id: ''
#     days: 60

# Default
galaxy_cleanup_objectstores: []

# Cron schedule for galaxy cleanup objectstores script
# Default: runs daily at 1:00 AM
galaxy_cleanup_minute: 0
galaxy_cleanup_hour: 1
