---
- name: "Deploy fixer upper script"
  copy:
    content: |
        #!/bin/bash
        # Workflows are currently being assigned to _default_ which is wrong
        # https://github.com/galaxyproject/galaxy/issues/8209
        . {{ galaxy_root }}/.bashrc
        while true; do
                psql -c "COPY (update workflow_invocation set handler = 'handler_main_' || (random() * 12)::integer where (state = 'new' and handler = '_default_') returning workflow_invocation.id) to STDOUT with CSV DELIMITER ',';" | ts
                sleep 5;
        done
    dest: /usr/bin/galaxy-fix-unscheduled-workflows
    owner: root
    group: root
    mode: 0755

- name: Add to cron
  cron:
    name: "Fix unscheduled workflows galaxyproject/galaxy#8209"
    minute: "*/20"
    job: pgrep -f /usr/bin/galaxy-fix-unscheduled-workflows > /dev/null || /usr/bin/galaxy-fix-unscheduled-workflows &
    user: "{{ galaxy_user.name }}"
