---

group_apt_keys:
  - keyserver: hkp://pgp.mit.edu:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

group_apt_repositories:
  - repo: deb https://apt.dockerproject.org/repo debian-jessie main

group_packages:
  - docker-engine
  - qemu-system-x86
  - make

group_files:
  - content: '# This file is managed by Ansible.  ALL CHANGES WILL BE OVERWRITTEN.\nw /sys/module/kvm/parameters/ignore_msrs - - - - 1\n'
    dest: '/etc/tmpfiles.d/qemu-ignore-msrs.conf'

# user_subvol_rm_allowed has to be set on the / mount (and that does not mean
# the btrfs root mounted at /btrfs). Could maybe do this with filesystems, but
# for now I just did it by hand.

local_users:
  - name: nate
    groups: kvm,docker
  - name: jenkins
    system: 'yes'
    groups: kvm,docker
    # Run /btrfs/snapshots/@starforge-<ver>/snap_for after creation
