---
- name: install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - bc
    - jq
    - lftp

- name: "Install credentials for FTP access"
  template:
    src: ftp-creds.txt
    dest: /etc/ftp-creds.txt
    owner: telegraf
    group: telegraf
    mode: 0640

- name: "Install galaxy API creds"
  template:
    src: gx-api-creds.json
    dest: /etc/gx-api-creds.json
    owner: telegraf
    group: telegraf
    mode: 0640

- name: "Install pip for galaxy script"
  pip:
    name: bioblend

- name: "Install simple-galaxy script"
  copy:
    src: simple-galaxy.py
    dest: /usr/local/bin/simple-galaxy
    owner: root
    group: root
    mode: 0755

- name: "Install simple-nagios-library script"
  copy:
    src: simple-nagios.sh
    dest: /usr/bin/simple-nagios-library
    owner: root
    group: root
    mode: 0755

- name: "Install simple-nagios-executor script"
  template:
    src: simple-nagios.sh
    dest: /usr/bin/simple-nagios
    owner: root
    group: root
    mode: 0755
