- type: dropbox
  id: dropbox
  label: Your Dropbox Files
  doc: Your Dropbox files - configure an access token via the user preferences
  accessToken: ${user.preferences['dropbox|access_token']}

- type: webdav
  id: b2drop
  doc: B2Drop WebDAV server
  url: https://b2drop.eudat.eu/remote.php/dav
  login: ${user.preferences['b2drop|username']} 
  password: ${user.preferences['b2drop|password']}

- type: posix
  root: '/data/5/galaxy_import/galaxy_user_data/covid-19/data/sequences/'
  id: covid19-raw-sequences
  label: COVID-19 FASTQ
  doc: COVID-19 RAW sequences in FASTQ format

- type: ftp
  id: ebi-ftp
  label: "EBI FTP server"
  doc: "EBI FTP server"
  host: "ftp.ebi.ac.uk"
  user: "anonymous"
  passwd: ""
  timeout: 10
  port: 21

- type: s3fs
  label: Genome Ark
  id: genomeark
  doc: Access to Genome Ark open data on AWS.
  bucket: genomeark
  anon: true

- type: s3fs
  label: 1000 Genomes
  id: 1000genomes
  doc: Access to the 1000 Genomes Project with human genetic variation, including SNPs, structural variants, and their haplotype context.
  bucket: 1000genomes
  anon: true

- type: s3fs
  label: The Cancer Genome Atlas
  id: tcga-2-open
  doc: Access to the Cancer Genome Atlas (TCGA)
  bucket: tcga-2-open
  anon: true

- type: s3fs
  label: COVID-19 Data Lake
  id: covid19-lake
  doc: A centralized repository of up-to-date and curated datasets on or related to the spread and characteristics of the novel corona virus (SARS-CoV-2) and its associated illness, COVID-19
  bucket: covid19-lake
  anon: true

- type: s3fs
  label: Encyclopedia of DNA Elements (ENCODE)
  id: encode-public
  doc: The Encyclopedia of DNA Elements (ENCODE) Consortium is an international collaboration of research groups funded by the National Human Genome Research Institute (NHGRI)
  bucket: encode-public
  anon: true
