default:
  masthead:
    color: "#003399"

lightblue:
  masthead:
    color: "#384E77"
    text:
      color: white
      hover: "#E6F9AF"
      active: white
    link:
      color: transparent
      hover: transparent
      active: "#18314F"

pride:
  masthead:
      color: >
        linear-gradient(120deg,
          #3c476d 0px 200px,
          #fdda0f 202px 210px,
          #fff 212px 220px,
          #f4b0c9 222px 230px,
          #7ccee6 232px 240px,
          #93540c 242px 250px,
          #000 252px 260px,
          transparent 262px),
        linear-gradient(270deg,
          #3c476d 0px 120px,
          #3c476d00 120px),
        linear-gradient(180deg,
          #FE0000 16.66%,
          #FD8C00 16.66% 33.32%,
          #FFE500 33.32% 49.98%,
          #119F0B 49.98% 66.64%,
          #0644B3 66.64% 83.3%,
          #C22EDC 83.3%)
      text:
        color: white
        hover: gold
        active: white
      link:
        color: "#3c476d"
        hover: "#323a53"
        active: "#6170a6"

smoky:
  masthead:
    color: "#0C0F0A"
    text:
      color: white
      hover: "#FBFF12"
      active: white
    link:
      color: transparent
      hover: transparent
      active: "#FF206E"
