preferences:
    use_cached_job:
      description: Do you want to be able to re-use previously run jobs ?
      inputs:
        - name: use_cached_job_checkbox
          label: Do you want to be able to re-use  equivalent jobs ?
          type: boolean
          checked: false
          value: false
          help: If you select yes, you will be able to select for each tool and workflow run if you would like to use this feature.

    localization:
        description: Localization
        inputs:
            - name: locale
              label: Prefered language
              type: select
              required: False
              options:
                  - [Navigator default, auto]
                  - [Chinese, zh]
                  - [English, en]
                  - [French, fr]
                  - [Japanese, ja]

    distributed_compute:
        description: Use distributed compute resources
        inputs:
            - name: remote_resources
              label: Remote resources id
              type: select
              required: False
              options:
                  - ["Select the remote resources", None]
                  - ["default - Galaxy will decide where to put your job", None]
                  - ["Joint remote GPU cluster using docker engine - Galaxy will decide where to put your job", remote_condor_cluster_gpu_docker]
                  - ["Joint remote CPU cluster using singularity engine - Galaxy will decide where to put your job", remote_condor_cluster_singularity]
                  - ["Freiburg (Germany) - de.NBI cloud - singularity", remote_cluster_mq_de01]
                  - ["Freiburg (Germany) - de.NBI cloud - docker", remote_cluster_mq_docker_de01]
                  - ["Freiburg (Germany) - de.NBI cloud - singularity, 2wd true", remote_cluster_mq_singularity_2wdtrue_de01]		  
                  - ["TÃ¼bingen (Germany) - de.NBI cloud", remote_cluster_mq_de02]
                  - ["Freiburg (Germany) - de.NBI cloud GPU", remote_cluster_mq_de03]
                  - ["Freiburg (Germany) - de.NBI cloud GPU - docker", remote_cluster_mq_docker_de03]
                  - ["Rennes (France) - GenOuest bioinformatics", remote_cluster_mq_fr01]
                  - ["Bari (Italy) - RECAS", remote_cluster_mq_it01]
                  - ["Bari (Italy) - RECAS 2", remote_cluster_mq_it02]
                  - ["Palermo (Italy) - GARR, 2wd true", remote_cluster_mq_2wdtrue_it03]
                  - ["Palermo (Italy) - GARR, 2wd falsef", remote_cluster_mq_2wdfalse_it03]
                  - ["Lisbon (Portugal) - Tecnico ULisboa", remote_cluster_mq_pt01]
                  - ["Oxfordshire (UK) - Diamond Light Source", remote_cluster_mq_uk01]
                  - ["Oxfordshire (UK) - Diamond Light Source - GPUs on docker", remote_cluster_mq_docker_uk01]
                  - ["Brussel (Belgium) - VIB", remote_cluster_mq_be01]
                  - ["Espoo (Finland) - CSC", remote_cluster_mq_fi01]
                  - ["Bergen (Norway) - UIB", remote_cluster_mq_no01]
                  - ["Barcelona (Spain) - BSC", remote_cluster_mq_es01]

    ega_account:
        description: Your EGA (European Genome Archive) account
        inputs:
            - name: username
              label: Username
              type: text
              required: False
            - name: password
              label: Password
              type:  password
              required: False

    dropbox:
        description: Your Dropbox account
        inputs:
            - name: access_token
              label: Dropbox access token
              type: password
              required: False
              
    b2drop:
        description: Your B2DROP account (https://b2drop.eudat.eu/)
        inputs:
            - name: username
              label: Username
              type: text
              required: False
            - name: password
              label: Password
              type:  password
              required: False

    omero_account:
        description: Your OMERO instance connection details
        inputs:
            - name: username
              label: Username
              type: text
              required: False
            - name: password
              label: Password
              type:  password
              required: False

    ena_webin_account:
        description: Your ENA Webin account details
        inputs:
            - name: webin_id
              label: ENA Webin ID
              type: text
              required: False
            - name: password
              label: Password
              type:  password
              required: False
