---
- name: Install cleanup objectstore script
  template:
    src: "{{ item }}.j2"
    dest: "/usr/local/bin/{{ item }}"
    mode: "0555"
  with_items:
    - "galaxy_cleanup_objectstores.sh"

- name: Schedule Galaxy cleanup objectstore script
  ansible.builtin.cron:
    name: "Galaxy cleanup objectstores"
    job: "/usr/local/bin/galaxy_cleanup_objectstores.sh"
    minute: "{{ galaxy_cleanup_minute | default(0) }}"
    hour: "{{ galaxy_cleanup_hour | default(1) }}"
    user: "{{ galaxy_user.name }}"
