private_token: {{ pulsar_private_token }}
staging_directory: /data/jwd04/galaxy_db/pulsar_staging/
tool_dependency_dir: /data/dnb01/galaxy_db/pulsar_dependencies/

managers:
  _default_:
    type: queued_condor
