---
admin_packages:
  - vim
  - htop
  - atop
  - strace
  - jq
  - iftop
  - wget
  - curl
  - tmux
  - git
  - nmap
  - tcpdump
  - net-tools
  - unzip
  - mutt
  - byobu
  - tmpwatch
  # centos specific
  - setools-console
  - yum-utils
  - bind-utils

