---
galaxy_info:
  author: The Galaxy Project
  description: Installs a VGCN monitoring script and a Telegraf configuration file
    to monitor the VGCN nodes.
  company: The Galaxy Project
  license: MIT
  min_ansible_version: 2.5
  platforms:
  - name: EL
    versions:
    - 8
    - 9
  galaxy_tags:
  - system
  - monitoring
dependencies: []