---

cvmfs_repositories:
  - repository: data.galaxyproject.org
    stratum0: cvmfs0-psu0.galaxyproject.org
    owner: root
    server_options:
      - CVMFS_AUTO_TAG=false
      - CVMFS_GARBAGE_COLLECTION=true
      - CVMFS_AUTO_GC=true

# old docker repo, docker now installed by the `docker` role
host_yum_repositories:
  - name: dockerrepo
    state: absent
    #contents:
    #  name: Docker Repository
    #  state: absent
