---

cvmfs_repositories:
  - repository: test.galaxyproject.org
    stratum0: cvmfs0-tacc0.galaxyproject.org
    owner: g2test
    server_options:
      - CVMFS_AUTO_TAG=false
      - CVMFS_GARBAGE_COLLECTION=true
      - CVMFS_AUTO_GC=false
      - CVMFS_IGNORE_XDIR_HARDLINKS=false
  - repository: main.galaxyproject.org
    stratum0: cvmfs0-tacc0.galaxyproject.org
    owner: g2main
    server_options:
      - CVMFS_AUTO_TAG=false
      - CVMFS_GARBAGE_COLLECTION=true
      - CVMFS_AUTO_GC=false
      - CVMFS_IGNORE_XDIR_HARDLINKS=false

# old docker repo, docker now installed by the `docker` role
host_yum_repositories:
  - name: dockerrepo
    state: absent
    #contents:
    #  name: Docker Repository
    #  state: absent

group_files:
  - src: files/apache/galaxy-installers.conf
    dest: /etc/httpd/conf.d/galaxy-installers.conf
    backup: true
