---

cvmfs_repositories:
  - repository: data.galaxyproject.org
    stratum0: cvmfs0-psu0.galaxyproject.org
    owner: g2test
    server_options:
      - CVMFS_AUTO_TAG=false
      - CVMFS_GARBAGE_COLLECTION=true
      - CVMFS_AUTO_GC=true

group_users:
  - name: g2test
    uid: 819456
    group: G-803372
    comment: "Galaxy Test"
    home: /home/g2test
    shell: /bin/bash
  - name: g2main
    uid: 819800
    group: G-803372
    comment: "Galaxy Main"
    home: /home/g2main
    shell: /bin/bash

group_groups:
  - name: G-803372
    gid: 803372
