---

linux_console: ttyS1,115200n8

host_apt_keys:
  - url: 'http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key'

host_apt_repositories:
  - repo: 'deb http://http.debian.net/debian jessie-backports main contrib non-free'
  - repo: 'deb http://pkg.jenkins-ci.org/debian binary/'

host_packages:
  - git
  - postgresql-9.4
  - python-virtualenv
  - jenkins
  - npm
  - nodejs-legacy
  # TS packages
  - autoconf
  - automake
  - build-essential
  - gfortran
  - cmake
  - git-core
  - libatlas-base-dev
  - libblas-dev
  - liblapack-dev
  - openssl
  - python-dev
  - python-setuptools
  - python-virtualenv
  - zlib1g-dev
  - libyaml-dev
  - subversion
  - python-dev
  - pkg-config
  - unzip
  - docker.io
  - samtools
  - sudo
  - curl

local_users:
  - name: jenkins
    groups: docker

# Note ~jenkins/.ssh/config is done by hand to make this work - need to put that in Ansible
# Maybe this? https://github.com/gaqzi/ansible-ssh-config
crontabs:
  - id: jenkins_backup
    name: Jenkins Backup
    user: jenkins
    hour: 22
    minute: 0
    job: rsync -av --delete --exclude='jobs/*/workspace*' /var/lib/jenkins/ zfsdump-leeroy@westvleteren.galaxyproject.org:/zones/westvleteren/backup/leeroy/jenkins && ssh -T zfsdump-leeroy@westvleteren.galaxyproject.org -- /usr/sbin/zfs snapshot zones/westvleteren/backup/leeroy/jenkins@`date -u +\%Y\%m\%dT\%H\%M\%SZ`
