---
- name: Ensure boto is available
  pip:
    name: boto
    state: latest

- name: Set DNS entries
  route53:
    command: create
    zone: "usegalaxy.eu"
    record: "{{ item }}"
    type: A
    ttl: 7200
    value: "{{ ansible_default_ipv4.address }}"
    wait: yes
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    overwrite: true
  with_items: "{{ server_names }}"
  when: set_dns | default(true)

- name: Template cert refresh command
  template:
    src: refresh.sh
    dest: /usr/sbin/cert-refresh
    owner: root
    group: root
    mode: 0755
  register: refresh_command

- name: Execute cert refresh if domains have changed
  command: /usr/sbin/cert-refresh
  when: refresh_command.changed

- name: Execute haproxy restart with new certs
  command: /etc/letsencrypt/renewal-hooks/post/haproxy.sh
  when: refresh_command.changed
