apollo_version: 2.4.1
apollo_tmp_file: "/tmp/apollo-{{ apollo_version }}.zip"
tomcat_apollo_webapp_dir: /usr/share/tomcat/webapps/apollo/

apollo_data_directory: /data/dnb01/apollo

apollo_db_username: apollo
#apollo_db_password:
apollo_db_uri: jdbc:postgresql://sn03.bi.uni-freiburg.de:5432/apollo
apollo_chado_username: apollo
#apollo_chado_password:
apollo_chado_uri: jdbc:postgresql://sn03.bi.uni-freiburg.de:5432/chado

apollo_admin_username: admin@usegalaxy.eu
#apollo_admin_password:
apollo_admin_firstname: UseGalaxy.eu
apollo_admin_lastname: Admin
