---
- set_fact:
    plugin_config_monitor_galaxy_queue:
      galaxy_monitor_queue:
        plugin: "exec"
        config:
          - commands = ["{{ custom_telegraf_env }} /usr/bin/gxadmin iquery queue-overview --short-tool-id"]
          - timeout = "15s"
          - data_format = "influx"
          - interval = "1m"

- set_fact:
        telegraf_plugins_extra: "{{ telegraf_plugins_extra | combine(plugin_config_monitor_galaxy_queue) }}"
