http:
  routers:
    gdpr-rtr:
      rule: "(Host(`usegalaxy.eu`) || HostRegexp(`^.+\\.usegalaxy\\.eu`)) && (PathPrefix(`/gdpr`) || PathPrefix(`/terms`))"
      service: gdpr
      entryPoints:
        - websecure
      tls:
        certResolver: "route53"
        domains:
          - main: "usegalaxy.eu"
            sans:
              - "*.usegalaxy.eu"
      middlewares:
        - replace-terms
  middlewares:
    replace-terms:
      replacePath:
        path: "/gdpr"
