{{define "subdomain"}}
    prox-{{ . }}:
      rule: HostRegexp(`^.+\\.{{ . }}\\.usegalaxy.eu`)
      service: usegalaxy-eu
      entryPoints:
        - websecure
      tls:
        certResolver: "route53"
        domains:
          - main: "{{ . }}.usegalaxy.eu"
            sans:
              - "*.ep.interactivetool.{{ . }}.usegalaxy.eu"
              - "*.{{ . }}.usegalaxy.eu"
{{end}}

http:
  routers:
{{template "subdomain" "assembly"}}
{{template "subdomain" "nanopore"}}
{{template "subdomain" "erasmusmc"}}
{{template "subdomain" "climate"}}
{{template "subdomain" "hicexplorer"}}
{{template "subdomain" "annotation"}}
{{template "subdomain" "metabolomics"}}
{{template "subdomain" "metagenomics"}}
{{template "subdomain" "microbiome"}}
{{template "subdomain" "microgalaxy"}}
{{template "subdomain" "microbiology"}}
{{template "subdomain" "biodiversity"}}
{{template "subdomain" "rna"}}
{{template "subdomain" "graphclust"}}
{{template "subdomain" "ecology"}}
{{template "subdomain" "proteomics"}}
{{template "subdomain" "clipseq"}}
{{template "subdomain" "cheminformatics"}}
{{template "subdomain" "imaging"}}
{{template "subdomain" "test"}}
{{template "subdomain" "beta"}}
{{template "subdomain" "streetscience"}}
{{template "subdomain" "singlecell"}}
{{template "subdomain" "humancellatlas"}}
{{template "subdomain" "ml"}}
{{template "subdomain" "live"}}
{{template "subdomain" "plants"}}
{{template "subdomain" "virology"}}
{{template "subdomain" "lite"}}
{{template "subdomain" "covid19"}}
{{template "subdomain" "africa"}}
{{template "subdomain" "india"}}
{{template "subdomain" "spatialomics"}}
{{template "subdomain" "materials"}}
{{template "subdomain" "phage"}}
{{template "subdomain" "earth-system"}}
{{template "subdomain" "cancer"}}
{{template "subdomain" "aqua"}}
{{template "subdomain" "eirene"}}
{{template "subdomain" "astronomy"}}
