---
# Certs
- name: mkdir
  file:
    path: "~/.docker"
    state: directory
    mode: '0750'

- name: Setup docker for user
  copy:
    src: "{{ item }}"
    dest: "~/.docker/{{ item }}"
    mode: "0640"
  with_items:
    - ca.pem
    - cert.pem
    - key.pem
