---
# Firewall
firewall_ip_prefix_trusted:
  - 10.4.68.0/24
firewall_ip_prefix_internal:
  - 10.4.68.0/24
  - 10.5.67.0/24
  - 10.5.68.0/24
  - 132.230.68.0/24
  - 132.230.223.0/24
  - 132.230.224.0/24
  - 10.5.153.0/24
  - 132.230.153.0/25
  - 10.23.0.0/16
  - 10.126.0.0/16
firewall_internal_services:
  - ssh
firewall_public_services: []
