---

- name: Tasks for "base environment" hosts
  hosts: baseenv
  remote_user: centos
  become: yes
  become_method: sudo
  pre_tasks:
    - name: Locate secret group variable files
      local_action:
        module: stat
        path: "{{ inventory_dir }}/secret_group_vars/{{ item }}.yml"
      become: no
      with_items: "{{ group_names }}"
      register: secret_group_vars
      tags: always
    - name: Include secret group variables
      local_action:
        module: "include_vars {{ item.stat.path }}"
      become: no
      with_items: "{{ secret_group_vars.results }}"
      when: item.stat.exists
      tags: always
  roles:
    - role: requiretty        # Disable requiretty for Ansible ssh pipelining
      tags: initial,requiretty
    - role: geerlingguy.repo-epel
      tags: packages
    - role: packages          # Install packages
      tags: system,packages
    - role: users             # Create users and set up authentication keys
      tags: system,users
    - role: paths             # Configure path permissions, filesystems
      tags: system,paths
    - role: copy              # Copy arbitrary files/templates
      tags: system,copy
    - role: cron              # Create cron jobs
      tags: system,cron
    - role: services          # Manage services
      tags: system,services
  tags: initial

- name: Filesystem tasks
  hosts: controllers:galaxynodes
  remote_user: centos
  become: yes
  become_method: sudo
  roles:
    - role: packages
      tags: packages
    - role: cvmfs
      tags: cvmfs
    - role: jetstream_nfs
      tags: nfs

# This has to be last for slurm elastic (everything must be configured/done when slurmd starts)
- name: Tasks for slurm hosts
  hosts: slurmservers:slurmclients
  remote_user: centos
  become: yes
  become_method: sudo
  vars_files:
    - secret_group_vars/slurmclients.yml
  roles:
    - role: slurm
      tags: slurm
